### PR TITLE
Answers

### PR DESCRIPTION
**Pull request by JaiSharmaTech**
Finished the hussle to display and post answer. also added comments field in answer to store comments.

### CODE REVIEW

**Review by KartikeyKakaria — APPROVED** [review]
Nice! but i;d recommend some improvements

**Comment by KartikeyKakaria** [comment]
For now i have approved these changes but more things need to be improved , only in frontend the backend is fine

**Comment by JaiSharmaTech** [comment]
Like?

**Comment by KartikeyKakaria** [comment]
Like Improvements in the design of the answers display yeah kinda like that, rest is fine.

**Comment by KartikeyKakaria** [comment]
P.S. I really liked the idea of storing comments in the answers schema, i was gonna create a another one of them :)

**Comment by JaiSharmaTech** [comment]
Thanks :)

**Pull request merged**
